# Site settings
title: Matteo Magni | Just Another Geek
email: matteo@magni.me
description: Just Another Geek!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://magni.me" # the base hostname & protocol for your site
twitter_username: ilbonzo
github_username:  ilbonzo
name: Matteo Magni
# Build settings
markdown: kramdown
